version: '3'

services:
  mongodb:
    container_name: mongodb
    image: mongo:7.0-rc-jammy
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - ./dbdata:/data/db

volumes:
  dbdata:
